wso2/apim-test-integration

Scenario06/README.md, Scenario06/base-setup.sh, Scenario06/infra.sh, Scenario06/jmeter/01-Solution-06-ApplicationLevelThrottling.jmx, Scenario06/jmeter/06-post-scenario-steps.sh, Scenario06/jmeter/06-pre-scenario-steps.sh, Scenario06/resources/01-config.sh, Scenario06/resources/user.properties, Scenario06/teardown.sh
Adding automation script for apim solutions scenario 6 and add other supported scripts.
Creating jmx script using jmeter which will be able to run on testgrid.
Scrips available :
*01-Solution-06-ApplicationLevelThrottling.jmx*
For scenario 06 from APIM solution described [1]
[1] <https://docs.google.com/document/d/1YTcqeywgLR47NZY3xWwc-jJfREjhhVl2vgAAasZhN3A/edit#>
=> automation script for apim solutions' scenario 6

Scenario01/jmeter/01-Solution1-PublicPartnerPrivateAPI.jmx, Scenario01/jmeter/02-Solution1-OwnershipAndColDevelopment.jmx, Scenario01/resources/UserAndRoleCreation.csv, Scenario01/resources/UserDetails.csv, Scenario01/resources/ViewAPI_CreatedByAdmin.csv
This will add the initial script for following
```
Managing Ownership and Development APIs 
- Each business units are responsible for their APIs and data. Some of them having sensitive data. They -need to consider security and controllability while providing value to the other business units.
- Able to restrict API (and its development) by business units
- Eg. APIs developed by financial business unit should be able to restrict (view/edit) to other business units
- Selected APIs should be able to share with different business units (edit and view)
```
=> Add Ownership and Development of APIs initial script

scenario-mapper.yaml, scenario01/jmeter/01-post-scenario-steps.sh, scenario01/jmeter/01-pre-scenario-steps.sh, scenario03/jmeter/01-Scenario03-App-Development-with-APIs.jmx, scenario03/resources/user.properties, scenario04/README.md, scenario04/jmeter/01-Scenario04-ManageLifeCycle.jmx, scenario04/resources/user.properties, scenario05/README.md, scenario09/README.md
1. Update scenario04 with product-profiles' host and ports
2. fixes for scenario01 and scenario05
=> update scripts with hostnames of product-profiles

scenario03/README.md, scenario05/jmeter/01-Solution-05-APIVersioning.jmx, scenario05/resources/user.properties
Scenario05 update for making compatible with 2.2.0 release
=> updated scenario05 script as compatible to 2.2.0

scenario03/jmeter/01-Scenario03-App-Development-with-APIs.jmx, scenario03/resources/user.properties
Change script to work with 2.2.0 and introduced nio http port for MSF4J service to call store.
=> Change script to work with 2.2.0

scenario01/jmeter/01-Solution1-PublicPartnerPrivateAPI.jmx, scenario01/jmeter/02-Solution1-OwnershipAndColDevelopment.jmx, scenario01/jmeter/03-Solution1-DeveloperOptimizedAPIDevelopment.jmx, scenario01/resources/user.properties
Made changes to run on apim 2.2.0
=> Made changes to run on apim 2.2.0

apps/Phone-Service/src/main/java/org/phone/service/Application.java, apps/Phone-Service/src/main/java/org/phone/service/PhoneOrder.java
> Update license header year of phone-service webapp
=> Update license header year of phone-service webapp

testgrid.yaml
> Contains changes related to renaming scenario-mapper.yaml to testgrid.yaml with property structure changes.
> Resolves #23 
> Adding a scenario tests configuration file to run on TestGrid
> Modify yaml file to match the TestGrid specified structure
=> Convert scenario-mapper.yaml to testgrid.yaml

scenario05/jmeter/01-Solution-05-APIVersioning.jmx, scenario05/resources/user.properties
> Fix sol 05 to make APIM 220 compatible
=> Fix sol 05 to make APIM 220 compatible

integration-tests/Configure_Product.py, integration-tests/config.yml
> The purpose of this PR is to add a script to configure a wso2 product to run integration tests against the configured product.
> This python script is able to configure a wso2 product for a given DB. In other words, it modifies given data sources in the product and integration pom files and compresses the product. Thereafter this compressed product could be used to run integration tests.  The config.yml file is used to maintain configuration details of the product. based on the data in the configuration file, python script does modifications to the product.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
- Integration tests
> N/A
- Ran FindSecurityBugs plugin and …
=> Add the product configuring script

integration-tests/run-scenario.sh
Prints each command before its execution
=> Prints each command before its execution

integration-tests/do-run.py
The script do-run.py is the execution point of the product's integration tests which supposed to run on TestGrid
The script include following functions
- Cloning the product repo
- Download last released pack from Jenkins
- Setting up the databases(create and execute product scripts)
- Running the external python script to configure the product(product config python script)
- Running product's integration tests
##ToDo
-Script needs to be improve to support all the other required environments(OS, DB)
=> add do-run.py for integration test execution

integration-tests/run-scenario.sh
=> Fix run-scenario.sh

integration-tests/do-run.sh
- Fix to send user inputs where calling python script
- Fix for DB names
=> Fix for insert user variable to call python script and fix for DB names

integration-tests/Configure_Product.py, integration-tests/const.py
> The purpose of this PR is to removing the config.yaml file.
> In order to run the Configure_Product.py it is required to pass command line parameters. Those are product_name, product_id, and database_config.  Since config.yaml file is removed, added const.py file to maintain constant values.
Note:- After integrate do_run.py file we can remove parameter passing option.
> OS - UBUNTU 18.04
=> Remove config.yaml file

integration-tests/do-run.py
-  improve the do-run.py : manipulations for product_distribution download url
=> improvements on do-run.py

integration-tests/run-scenario.sh
update run-scenario to run do-run.py
=> update run-scenario to run do-run.py

integration-tests/run-scenario.sh
Creates the REMOTE_WORKSPACE_DIR_UNIX dir before do-run.sh
=> Creates the REMOTE_WORKSPACE_DIR_UNIX dir before do-run.sh

integration-tests/do-run.sh
- Add mssql and oracle db scripts to do-run.sh
- Add workspace directory property to read from file
=> Improved with mssql and oracle DB populate script

integration-tests/configure_product.py
> The purpose of this PR is to fix Oracle related issues.
> For Oracle DB, DB accessing pattern, DB URL pattern etc are different from other DB engines. Hence modified the data sources modifying logic and consider Oracle as a specific case.
=> Fix Oracle DB related issue

integration-tests/do-run.sh, integration-tests/run-scenario.sh
Add waiting for deployment startup logic
=> Add waiting for deployment startup logic

integration-tests/do-run.sh
- Fix patch and improve database script.
=> Fix patch and improve database script

integration-tests/do-run.sh
- Improve the script with property read logic
=> Improve the script with property read logic

integration-tests/do-run.py, integration-tests/do-run.sh
Fix the DB username password param names
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Fix the DB username password param names

integration-tests/do-run.py
Fixes for adding missing parameter for run_oracle_script() method calls.
=> fix oracle db operations

integration-tests/const.py, integration-tests/do-run.py, integration-tests/requirements.txt
> The purpose of this PR is to improve python scripts.
> Since property file structure and some values are changed, python scripts also modified. Further adding requirements.txt file to identify required python external packages.
> Operating System - UBUNTU 18.04
=> Improve python scripts

integration-tests/do-run-executor.sh, integration-tests/requirements.txt, integration-tests/run-scenario.sh
> The purpose of this PR is to add do-run-executor.sh.
=> Add do-run-executor.sh

integration-tests/do-run-executor.sh, integration-tests/run-scenario.sh
Fix working dir for py
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix working dir for py

integration-tests/const.py, integration-tests/do-run.py
=> fixed with correct DB engine names

integration-tests/run-scenario.sh
`nc` command immediately provide a connection refused and exit in some ec2 instances while some other instances waits upto 2mins before throwing a time out exception. To be fail-safe, we'll need this at around 20.
> Link(s) to product documentation that addresses the changes of this …
=> Increase CONNECT_RETRY_COUNT to 20

integration-tests/do-run.py
This will fix mb db script file path in do-run.py script
=> fix mb db script file path

integration-tests/do-run.py
enable mvn batch-mode to reduce log prints at CI console.
=> enable mvn batch-mode

integration-tests/const.py, integration-tests/do-run-executor.bat, integration-tests/do-run.py
> The purpose of this PR is to add "do-run-executor.bat" file.
> In order to create python **virtualenv** in the Windows, it is required to have an equivalent file to "do-run-executor.sh" for Windows as well. Hence created "do-run-executor.bat" file. Since key values in the property files have changed modified the python constant file as well.
> OS - Windows -7
=> Add do-run-executor.bat file

integration-tests/const.py
> The purpose of this PR is to modify the python constant file.
> As a result of property file change, modified the python constant file as well
=> Change the oracle db engine name

integration-tests/configure_product.py
> The purpose of this PR is to fix pom file modifying issue. 
=> Fix pom file modifying issue

integration-tests/configure_product.py, integration-tests/const.py, integration-tests/run-intg-test.py
> The purpose of this PR is to fix DB creating issues.
=> Fix DB creating issues

integration-tests/configure_product.py, integration-tests/const.py, integration-tests/run-intg-test.py
> The purpose of this PR is to adding log files storing method after complete the integration tests running.
> It is required to create a logs folder in the workspace and store log files in there. Thereafter tinkerer agent can get these log files located in the workspace/logs older.
> OS -UBUNTU-18.04
=> Add log files storing method

integration-tests/const.py
> The purpose of this PR is to fix mssql URL issue.
=> Fix mssql URL issue

integration-tests/configure_product.py, integration-tests/const.py, integration-tests/run-intg-test.py
> The purpose of this PR is to improve product name generating method 
> Construct the product name and product zip file name by reading distribution pom file. Further, fix **api-import-export-test.war** file not found issue by building **api-import-export-test** module.
=> Improve product name generating method

integration-tests/configure_product.py, integration-tests/run-intg-test.py
> The purpose of this PR is to copy the distribution into local m2
=> Copy distribution into local m2

integration-tests/configure_product.py
> The purpose of this PR is to fix distribution copying issue into local m2.
=> Fix distribution copying issue

integration-tests/configure_product.py
> The purpose of this PR is to fix issues in distribution copying to local m2, on windows OS.
=> Fix windows distribution copying issue

integration-tests/configure_product.py, integration-tests/const.py, integration-tests/run-intg-test.py
> The purpose of this PR is to improve the source.
> Modified git checkout method, product build method by removing printing download logs on the console, removed unnecessary methods, modified source to support other wso2 products.
=> In order to run integration tests against other wso2 products Improve the source 

integration-tests/run-intg-test.py
> The purpose of this PR is to improve the property file validating method.
=> Improve property file validating method

integration-tests/testng.xml
Updated the testng xml file excluding the test cases that fail in any infra combination
Achieve all test successful build result
comment out the failing test cases.
=> Update custom testng file

integration-tests/run-intg-test.py, integration-tests/testng.xml
=> Update the custom testng logic

integration-tests/run-intg-test.py
> Remove the run on branch logic
> Execute integration test logic
=> Exclude run on branch logic

integration-tests/testng.xml
Enable 2 test cases from custom testng.xml file
=> Enable testng.xml file

integration-tests/testng.xml
Make tests fail in few infra combinations as possible
generate email report with failing and passing infra combinations
=> Update testng.xml for failing test cases

integration-tests/configure_product.py, integration-tests/run-intg-test.py
> The purpose of this PR is to introduce TEST_MODE property.
> Introduce four different test modes. Those are
- RELEASE - When testing product release. (i.e. RC, milestone etc) 
- DEBUG - When testing the whole integration test running flow via TestGrid (this is required to TestGrid team)
- SNAPSHOT - When verifying fixes for failed test cases.
- WUM - When verifying WUM update and WUM updated distribution.
> JDK - ORACLE-JDK8
> DB - MySQL5.7
=> Introduce TEST_MODE property and modify the source

integration-tests/run-scenario.sh
Reverts wso2/apim-test-integration#135
=> Revert "Change key-file property name"

integration-tests/configure_product.py, integration-tests/const.py, integration-tests/run-intg-test.py, integration-tests/run-scenario.sh
Purpose of this is to add the new Test mode WUM changes and run the integration test scenarios with WUM update for APIM.
Added new method to into cloud formation script and change run-intg, configure_product python files existing logics in order to support with WUM
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Add WUM changes

integration-tests/run-scenario.sh
Reverts wso2/apim-test-integration#137
=> Revert "Revert "Change key-file property name""

integration-tests/configure_product.py
Update datasource configuration in configure-product.py with defaultAutoCommit=true for all the databases.
=> update database configuration with defaultAutoCommit=true

integration-tests/configure_product.py
Reverts wso2/apim-test-integration#140
=> Revert "made autoCommit true for mysql"

integration-tests/configure_product.py
Reverts wso2/apim-test-integration#142
=> Revert "update database configuration with defaultAutoCommit=true"

integration-tests/run-intg-test.py
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Get the latest tag from the current branch

integration-tests/run-scenario.sh
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Update output.properties path

integrationtests/run-intg-test.py, integrationtests/run-scenario.sh
Purpose of this change is to modify the testgrid common script to support with the wum test mode.  
This PR includes the product build path change which is specific to wum. As well as copied the clone_product_repo_wum.sh file which is used to clone the product repo from the support branch. 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable …
=> Add wum product clone repo path changes and change the build path for WUM test mode

integrationtests/run-scenario.sh
Copy uat-nexus-settings.xml and wum update sh only for WUM test type
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the …
=> Copy uat-nexus-settings.xml and wum update sh only for WUM test type

integrationtests/run-scenario.sh
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Set windows password connect retry count 20 -> 40

scenario09/resources/user.properties
=> remove data
